export const BASE = 'BASE/';
export const SHOW_MODAL = `${BASE}SHOW_MODAL`;
export const HIDE_MODAL = `${BASE}HIDE_MODAL`;
export const MODAL_PROCESSING_STARTED = `${BASE}MODAL_PROCESSING_STARTED`;
export const MODAL_PROCESSING_STOP = `${BASE}MODAL_PROCESSING_STOP`;
